### ISSUE TITLE
My xAccount is on pangolin, but kton staking page tells me 'Wrong Network'

### ISSUE THREAD

**Issue by wuminzhe** [msgport/xaccount-ui#21]
<img width="1800" alt="image" src="https://github.com/darwinia-network/xaccount-ui/assets/1608576/9d798c95-068c-4e0b-8e91-ca750edd38a6">

**Comment by snoopy1412** [comment]
See also: #15

**Comment by wuminzhe** [comment]
After disconnecting, it works.
