### ISSUE TITLE
The transaction here is not correct.

### ISSUE THREAD

**Issue by wuminzhe** [msgport/xaccount-ui#26]
This is the source transaction. but I think there is no way to correct it.

<img width="576" alt="image" src="https://github.com/darwinia-network/xaccount-ui/assets/1608576/546fea1f-8285-49e2-a74d-cd1418b10d00">

**Comment by hackfisher** [comment]
Safe app SDK might have ways to feed back the tx on the target chain?

**Comment by wuminzhe** [comment]
> Safe app SDK might have ways to feed back the tx on the target chain?

I can provide the target tx through msgscan api, but it needs some time. So, once user triggered the tx, he can not have a correct target tx.
